### ISSUE TITLE
Shareable urls

### ISSUE THREAD

**Issue by IonicaBizau** [alysonla/open-source-monthly#7]
Would be neat to save somehow the selected organization(s) in url and then be able to share the url:

> `http://alysonla.github.io/open-source-monthly/?orgs=github,jillix`

Maybe something like that?

Nice project! :clap: :sparkles:

**Comment by alysonla** [comment]
Thanks for your comment @IonicaBizau !

Hope you are well!!  

Closing this out as I'm doing an issue clean up sweep. :)
